Repository suitenumerique/meet, pull requests merged in 2024-07, with the labels that each got.

#18 ♻️(frontend) reorganize starting frontend code
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/panda.config.ts
  src/frontend/public/fonts/sourcecodepro-regular-subset.woff2
  src/frontend/public/fonts/sourcesans3-bold-subset.woff2
  src/frontend/public/fonts/sourcesans3-it-subset.woff2
  src/frontend/public/fonts/sourcesans3-regular-subset.woff2
  src/frontend/src/App.tsx
  src/frontend/src/api/apiUrl.ts
  src/frontend/src/api/fetchRoom.ts
  src/frontend/src/api/fetchUser.ts
  src/frontend/src/api/queryKeys.ts
  src/frontend/src/features/auth/api/ApiUser.ts
  src/frontend/src/features/auth/api/fetchUser.ts
  src/frontend/src/features/auth/api/useUser.tsx
  src/frontend/src/features/auth/index.ts
  src/frontend/src/features/auth/utils/authUrl.ts
  src/frontend/src/features/rooms/api/ApiRoom.ts
  src/frontend/src/features/rooms/api/fetchRoom.ts
  src/frontend/src/features/rooms/components/Conference.tsx
  src/frontend/src/features/rooms/components/Join.tsx
  src/frontend/src/features/rooms/index.ts
  src/frontend/src/features/rooms/navigation/navigateToNewRoom.ts
  src/frontend/src/features/rooms/routes/Room.tsx
  src/frontend/src/features/rooms/utils/generateRoomId.ts
  src/frontend/src/layout/Box.tsx
  src/frontend/src/layout/BoxScreen.tsx
  src/frontend/src/layout/ErrorScreen.tsx
  src/frontend/src/layout/ForbiddenScreen.tsx
  src/frontend/src/layout/Header.tsx
  src/frontend/src/layout/NotFoundScreen.tsx
  src/frontend/src/layout/QueryAware.tsx
  src/frontend/src/layout/Screen.tsx
  src/frontend/src/navigation/navigateToHome.ts
  src/frontend/src/primitives/A.tsx
  src/frontend/src/primitives/Badge.tsx
  src/frontend/src/primitives/Bold.tsx
  src/frontend/src/primitives/Box.tsx
  src/frontend/src/primitives/Button.tsx
  src/frontend/src/primitives/Div.tsx
  src/frontend/src/primitives/H.tsx
  src/frontend/src/primitives/Hr.tsx
  src/frontend/src/primitives/Italic.tsx
  src/frontend/src/primitives/Link.tsx
  src/frontend/src/primitives/P.tsx
  src/frontend/src/primitives/Text.tsx
  src/frontend/src/primitives/index.ts
  src/frontend/src/queries/useUser.tsx
  src/frontend/src/routes/Conference.tsx
  src/frontend/src/routes/Home.tsx
  src/frontend/src/routes/NotFound.tsx
  src/frontend/src/styles/fonts.css
  src/frontend/src/styles/index.css
  src/frontend/src/styles/livekit.css
  src/frontend/src/utils/createRandomRoom.ts
Labels: noChangelog

#38 📝(release) document releasing new version
  docs/release.md
Labels: documentation

#68 🩹(frontend) fix ignored pre-join options
  src/frontend/src/features/rooms/components/Conference.tsx
Labels: bug

#39 📝(tilt) document running the application with Tilt
  README.md
Labels: documentation
